### ISSUE TITLE
Вывод во view данных из checkbox, select etc...

### ISSUE THREAD

**Issue by loveorigami** [Mirocow/yii2-eav#3]
Подключил модуль.
Создал eav-форму с чекбоксами и селектом.
Заполнил в модели. Сохранил.
![0001](https://cloud.githubusercontent.com/assets/98164/11238049/34a82efe-8df4-11e5-8bb3-a7319de74b2e.jpg)

Теперь хочу вывести эти данные во фронтенде.

Делаю, как
```php
<?php
  foreach($model->getEavAttributes()->all() as $attr){
    echo $model[$attr->name];
  }
?>
```
текстовые выводятся, а для селекта и чекбоксов получаю Id-шники...

```
[3,4] привет 6 классное описание 8
```
Как вместо цифр и массива можно получить значения (видео, треугольник и т.д..)?

**Comment by Mirocow** [comment]
```php
<?php
  foreach($model->getEavAttributes()->all() as $attr){
    print_r($model[$attr->name]['value']);
  }
?>
```
