### ISSUE TITLE
Не применяется миграция

### ISSUE THREAD

**Issue by DukeNsk** [Mirocow/yii2-eav#40]
Текст ошибки:
`*** applying m150821_133232_init
    > create table {{%eav_entity}} ... done (time: 0.173s)
    > create table {{%eav_attribute}} ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'entityId'
The SQL being executed was: CREATE TABLE `ae_eav_attribute` (
        `id` int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
        `entityId` int(11) DEFAULT 'NULL',
        `typeId` int(11) DEFAULT 'NULL',
        `type` varchar(50) DEFAULT '',
        `name` varchar(255) DEFAULT 'NULL',
        `label` varchar(255) DEFAULT 'NULL',
        `defaultValue` varchar(255) DEFAULT 'NULL',
        `defaultOptionId` int(11) DEFAULT 0,
        `description` varchar(255) DEFAULT 'NULL',
        `required` smallint(1) DEFAULT 0,
        `order` int(11) DEFAULT 0
) CHARACTER SET utf8 COLLATE utf8_general_ci ENGINE=InnoDB (D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\db\Schema.php:633)
#0 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\db\Command.php(854): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE `a...')
#1 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\db\Migration.php(260): yii\db\Command->execute()
#2 D:\OpenServer\domains\artengine.lh\vendor\mirocow\yii2-eav\src\migrations\m150821_133232_init.php(80): yii\db\Migration->createTable('{{%eav_attribut...', Array, 'CHARACTER SET u...')
#3 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\db\Migration.php(93): m150821_133232_init->safeUp()
#4 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(509): yii\db\Migration->up()
#5 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\console\controllers\BaseMigrateController.php(130): yii\console\controllers\BaseMigrateController->migrateUp('m150821_133232_...')
#6 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#7 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\base\InlineAction.php(55): call_user_func_array(Array, Array)
#8 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\base\Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#9 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\console\Controller.php(119): yii\base\Controller->runAction('up', Array)
#10 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\base\Module.php(454): yii\console\Controller->runAction('up', Array)
#11 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\console\Application.php(176): yii\base\Module->runAction('migrate/up', Array)
#12 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\console\Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#13 D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\base\Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#14 D:\OpenServer\domains\artengine.lh\yii(28): yii\base\Application->run()
#15 {main}
*** failed to apply m150821_133232_init (time: 0.215s)
`

**Comment by Mirocow** [comment]
была ошибочно закомичена. удалили
