### ISSUE TITLE
Не работает редактор

### ISSUE THREAD

**Issue by DukeNsk** [Mirocow/yii2-eav#43]
Пытаюсь реализовать следующую схему: 
Категории (Category), Типы товаров (Product Type), Товары (Product). Для категории назначается тип товара (связь по ID типа товара).

Все миграции прошли успешно. Необходимые таблицы созданы.

В Модели Товара (Product) пишу:
в behaviors:
`            'eav' => [
                'class' => \mirocow\eav\EavBehavior::className(),
                // это модель для таблицы object_attribute_value
                'valueClass' => \mirocow\eav\models\EavAttributeValue::className(),
            ],`

Метод для получения EAV-аттрибутов:
`    public function getEavAttributes()
    {
        return \mirocow\eav\models\EavAttribute::find()
            ->joinWith('entity')
            ->where([
                'categoryId' => $this->category->product_type_id,
                'entityModel' => $this::className()
            ]);
    }`

В модели типа товара (ProductType):
В behaviors:
`'eav' => [
                'class' => \mirocow\eav\EavBehavior::className(),
                // это модель для таблицы object_attribute_value
                'valueClass' => \mirocow\eav\models\EavAttributeValue::className(),
            ]`

Метод для получения атрибутов:

`public function getEavAttributes()
    {
        return \mirocow\eav\models\EavAttribute::find()
            ->joinWith('entity')
            ->where([
                'categoryId' => $this->id,
                'entityModel' => Product::className(),
            ]);
    }`

На странице редактирования типа товара  вставляю виджет для редактирования полей ($model — соответствующая модель класса ProductType):
`<?= \mirocow\eav\admin\widgets\Fields::widget([
        'model' => $model,
        'categoryId' => $model->id,
        'entityName' => $model->title,
        'entityModel' => 'app\modules\shop\models\Product',
        'url' => '/eav/admin/ajax/index',
        'urlSave' => '/eav/admin/ajax/save',
    ])?>`

Кроме того, подключил EAV-модуль в секцию "modules" конфига приложения:
`        'eav' => [
            'class' => 'mirocow\eav\Module',
        ],`

Однако, виджет Fields выводится в странном виде, поля можно добавлять, но они не сохраняются, на кнопке сохранения нет надписи (выглядит [так](https://drive.google.com/open?id=0B0h9DqN)), а в консоли отладчика Chrome при загрузке страницы ошибка: formbuilder_old.js:174 Uncaught TypeError: Formbuilder.templates[("view/base" + (intermediate value)(intermediate value)(intermediate value))] is not a function

Что я делаю не так?

**Comment by DukeNsk** [comment]
Поправка: [ссылка](https://drive.google.com/open?id=0B0h9DqNDUqSQLTNJN2s4RThRVXc) на скриншот

**Comment by Mirocow** [comment]
скайп mirocow

**Comment by Mirocow** [comment]
fixed
