### ISSUE TITLE
Не добавляются параметры

### ISSUE THREAD

**Issue by dukensk** [Mirocow/yii2-eav#44]
При нажатии кнопки сохранения в виджете, записи о параметрах не добавляются, а в лог падает ошибка:

Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`artengine`.`ae_eav_attribute`, CONSTRAINT `FK_Attribute_typeId` FOREIGN KEY (`typeId`) REFERENCES `ae_eav_attribute_type` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)' in D:\OpenServer\domains\artengine.lh\vendor\yiisoft\yii2\db\Command.php:844

Next exception 'yii\db\IntegrityException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`artengine`.`ae_eav_attribute`, CONSTRAINT `FK_Attribute_typeId` FOREIGN KEY (`typeId`) REFERENCES `ae_eav_attribute_type` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)
The SQL being executed was: INSERT INTO `ae_eav_attribute` (`name`, `type`, `entityId`, `typeId`, `label`, `order`, `description`) VALUES ('c1', NULL, 6, 0, NULL, 0, '')' in

**Comment by Mirocow** [comment]
fixed
