### ISSUE TITLE
Мелкий фикс в миграции

### ISSUE THREAD

**Issue by kovalenkos** [Mirocow/yii2-eav#45]
DB Postgres

Вместо 
'required' => Schema::TYPE_BOOLEAN . ' DEFAULT 1',
написать 
'required' => Schema::TYPE_BOOLEAN . ' DEFAULT true',

потому как возникает ошибка 
 create table {{%eav_attribute}} ...Exception: SQLSTATE[42804]: Datatype mismatch: 7 ОШИБКА:  колонка "required" имеет тип boolean, но тип выражения по умолчанию integer
HINT:  Перепишите выражение или преобразуйте его тип.

**Comment by Mirocow** [comment]
спасибо, поправим

**Comment by kovalenkos** [comment]
вам спасибо! только начинаю разбираться в вашей разработке

**Comment by Mirocow** [comment]
лучше использовать на данный момент релиз, так как дев ветка сейчас не рабочая

**Comment by kovalenkos** [comment]
надеюсь что я его и использую ) 

php composer.phar require --prefer-dist "mirocow/yii2-eav" "*"

**Comment by Mirocow** [comment]
```
php composer.phar require --prefer-dist "mirocow/yii2-eav" "@v0.6.1"
```

**Comment by kovalenkos** [comment]
спасибо

**Comment by 7krasov** [comment]
Всем привет. заполнял базу с помощью запуска миграции. в единственной миграции m150821_133232_init версии 0.6.1 таблица eav_entity не добавляется, но есть добавление в dump.sql . а так же в миграции нет вставок записей в таблицу. возможно, еще что-то не вынесено. планируете ли вы создание схемы и записей автоматом через миграцию? или же миграции не актуальны в данной версии и предполагается только заливка sql-файла? Спасибо

**Comment by ComradePashka** [comment]
аналогично с @7krasov поставил экстеншн, выполнил миграцию, роут eav/admin/entity/create eav/admin/entity/list выкидывают `The table does not exist: {{%eav_entity}}`

**Comment by Mirocow** [comment]
fixed
