### ISSUE TITLE
renderField не совсем понятен смысл

### ISSUE THREAD

**Issue by alien-art** [Mirocow/yii2-eav#48]
В Классе [ActiveField](https://github.com/Mirocow/yii2-eav/blob/master/src/widgets/ActiveField.php)
в методе renderField есть следующий код
`$eavModel = Html::getAttributeValue($model, $attribute);`
В случае если ранее этот EAV атрибут не существовал, или не заполянлся, то `$eavModel = null`
и дальше метод падает.
Даже если `$eavModel != null` метод упадет, так `Html::getAttributeValue($model, $attribute);` возвращает значение поля, а не объект и дальнейшие действия метода не выполнимы.
Если правильно понял задача это метода подготовить атрибут к рендеру, заполнив все необходимые свойства так?
p.s. пытаюсь понять принцип работы модуля и привести его в рабочее состояние.
Если что для связи icq: 5533427

**Comment by Mirocow** [comment]
skype: mirocow
Возможно уже пофиксил
