### ISSUE TITLE
Основное значение типа VARCHAR -> TEXT

### ISSUE THREAD

**Issue by evgenmil** [Mirocow/yii2-eav#5]
Здравствуйте.
Отличная доработка модуля!

Почему бы не изменить в таблице `eav_attribute_value` тип поля `VARCHAR` на `TEXT`?
Что вы думаете по этому поводу?

**Comment by Mirocow** [comment]
лучше подобный тип данных хранить отдельно, как вариант сделать еще 1 таблицу с типом текст, так как полей EAV может быть много и это сильно утяжелит таблицу

**Comment by evgenmil** [comment]
Согласен. Что-то я не подумал) Может на VARCHAR(1000) или и правду вывести в отдельную таблицу?

**Comment by Mirocow** [comment]
будут реализованы дополнительные поля в таблице или будет создана отдельная таблица

**Comment by Mirocow** [comment]
close
