### ISSUE TITLE
PDOException

### ISSUE THREAD

**Issue by mydesign** [Mirocow/yii2-eav#52]
exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`dbname`.`eav_attribute`, CONSTRAINT `FK_EntityId` FOREIGN KEY (`entityId`) REFERENCES `eav_entity` (`id`) ON DELETE CASCADE ON UPDATE NO ACTION)'

**Comment by Mirocow** [comment]
fixed. use migration
