### ISSUE TITLE
Bug: "Curse field C2"

### ISSUE THREAD

**Issue by mazurva** [Mirocow/yii2-eav#59]
To test, I add a text box first (it is the check), and save, reload the page and make sure that the editor showed this field. Then add the "drop-down list" and save, check that all recorded in a database. Reload the page, and the page loads, but see only the text box.
I struggled with this for a long time and that's what found out:

1. The field is automatically assigned a serial number and name with this number, and so if the text field is a named `c1`, the drop-down list is `c2`;
2. if you rename a field of `c2` to `c3` (or any other), it will appear in the editor;
3. any, followed by addition of the field is displayed normally, though more than 5 fields, I did not add.

Для тестирования я добавляю текстовое поле первым (оно проверочное) и сохраняю, перезагружаю страницу и убеждаюсь что редактор видит это поле. Потом добавляю "Выпадающий список", добавляю к нему опции и сохраняю, проверяю что в базу данных все записалось. Перезагружаю страницу и при загрузке страницы вижу только текстовое поле. 
Бился я с этим долго и вот что выяснил:

1. полям автоматически присваивается последовательный номер и имя с этим номером, так вот если текстовое поле это поле `c1`, то выпадающий список это `c2`;
2. если переименовать поле из `с2` в `с3` (или любое другое), то оно появиться в редакторе;
3. любое, последующее добавленное поле отображается нормально, правда больше 5 полей я не добавлял.

**Comment by Mirocow** [comment]
fixed
