### ISSUE TITLE
Ругается на отсутствие таблицы eav_entity

### ISSUE THREAD

**Issue by DukeNsk** [Mirocow/yii2-eav#6]
Добрый день. В ходе миграции не создается таблица eav_entity, после подключения виджета \mirocow\eav\admin\widgets\Fields, вводится ошибка о ее отсутствии.

**Comment by ignatenkovnikita** [comment]
Есть такое, решил просто sql из dump'a залить

**Comment by Mirocow** [comment]
как вариант миграции выполнить 

```sh
php yii migrate/up --migrationPath=@mirocow/eav/migrations
```

**Comment by Mirocow** [comment]
да похоже пропущена в мигации
