### ISSUE TITLE
Генерируется очень много запросов к БД

### ISSUE THREAD

**Issue by dukensk** [Mirocow/yii2-eav#62]
А это нормально, что при выводе товара с 6 дополнительными параметрами (2 выпадающих списка по 2 варианта в каждом и 4 поля ввода), генерируется порядка 270 запросов к БД, тогда как до подключения EAV было всего порядка 20 запросов?

**Comment by Mirocow** [comment]
нет, на данный момент не проводил анализ кол-ва обращений к бд
и не оптимизировал скорость
я сначала хочу написать весь необходимый функционал, а потом уже рефакторить для улучшения производительности и минимизации кол-ва запросов к бд

**Comment by dukensk** [comment]
Очень неоптимально работает получение value по $model[$attr->name]['value'] в цикле обхода атрибутов, я сделал  виджет для вывода аттрибутов с получением value и optionId вот так:
`$attribute->getEavAttributeValues()->select(['value', 'optionId'])->one()->toArray()`

это снизило количество запросов более, чем в 10 раз.

**Comment by Mirocow** [comment]
знаю

**Comment by dukensk** [comment]
Еще очень не повредил бы индекс по entityId в таблице eav_attribute_value

**Comment by mazurva** [comment]
@dukensk а пул реквест где? Хотя бы закинь виджет. В любом случае, спасибо.

**Comment by dukensk** [comment]
@mazurva пулл-реквест на добавление индекса отправил. Виджет немного отрефакторю и тоже отправлю.

**Comment by Mirocow** [comment]
где виджет, комрады?

**Comment by Mirocow** [comment]
fidex
