### ISSUE TITLE
Некорректно добавляется админ-панель

### ISSUE THREAD

**Issue by MuratDeveloper** [Mirocow/yii2-eav#70]
Доброго времени суток!
Добавил в конфиг:
```
 'modules' => [
        'eav' => [
             'class' => 'mirocow\eav\Module',
        ],
]
```
По адресу site/eav доступна главная страница админки, пишет "EAV Fields constructor". При нажатии на Create/List выводит 404 not found.
Что я делаю не так?
Спасибо.

Yii 2.0.10

**Comment by Mirocow** [comment]
да потому как это старый функционал и он постепенно удаляется, на этой странице будет инструкция по использованию модуля. Основной функционал модуля это бехавиор  и web интерфейс при редактировании ноды 

для вывода формы 
``` php
		<?php
		foreach($model->getEavAttributes()->all() as $attr){
				echo $form->field($model, $attr->name, ['class' => '\mirocow\eav\widgets\ActiveField'])
				->eavInput();
		}
		?>
```

и для редактирования и создания атрибутов

``` php
<?= \mirocow\eav\admin\widgets\Fields::widget([
											'model' => $model,
											'categoryId' => $model->id,
											'entityName' => 'Продукт',
											'entityModel' => 'app\models\Product',
									])?>
```

**Comment by Mirocow** [comment]
thxed
