### ISSUE TITLE
Добавление и редактирование AttributeValue прямо из главной модели

### ISSUE THREAD

**Issue by invizitor** [Mirocow/yii2-eav#75]
Хотелось бы для удобства прямо из модели продукта выставлять AttributeValue.

$model = Product::find()->where(['id' => 1])->one();
$model->EavModel->color = "blue";
$model->EavModel->packing = "12 kg";
$model->save();

Если в таблице не было записи соответствующего AttributeValue - то добавляется с новым значением,
если была, то обновляется.

entityId берется из $model->id
attributeId по его name

Спасибо.

**Comment by invizitor** [comment]
Если не подходит по формату () - то либо Exception, либо просто не обрабатывать.
(примерно так же, как и когда с ActiveForm данные приходят)

**Comment by Mirocow** [comment]
Прикрутил.
'''
$model = Product:findOne(1);
$model->c123 = 1;
$model->save();
'''

**Comment by invizitor** [comment]
Все гуд. Спасибо!
