### ISSUE TITLE
В чём может быть дело?

### ISSUE THREAD

**Issue by Elgorm** [Mirocow/yii2-eav#76]
Добрый день! Подключил модуль, выводится вот это 
![default](https://cloud.githubusercontent.com/assets/8758619/24836360/68b563fe-1d33-11e7-9cb0-db1402dbcbe7.PNG)
Но все ссылки выдают 404 ошибку
exception 'yii\base\InvalidRouteException' with message 'Unable to resolve the request "eav/admin/attribute/create".' in D:\OpenServer\domains\local.host\protected\vendor\yiisoft\yii2\base\Module.php:532 Stack trace: #0 D:\OpenServer\domains\local.host\protected\vendor\yiisoft\yii2\web\Application.php(102): yii\base\Module->runAction('eav/admin/attri...', Array) #1 D:\OpenServer\domains\local.host\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request)) #2 D:\OpenServer\domains\local.host\backend\index.php(21): yii\base\Application->run() #3 {main} Next exception 'yii\web\NotFoundHttpException' with message 'Страница не найдена.' in D:\OpenServer\domains\local.host\protected\vendor\yiisoft\yii2\web\Application.php:114 Stack trace: #0 D:\OpenServer\domains\local.host\protected\vendor\yiisoft\yii2\base\Application.php(380): yii\web\Application->handleRequest(Object(yii\web\Request)) #1 D:\OpenServer\domains\local.host\backend\index.php(21): yii\base\Application->run() #2 {main}

**Comment by Elgorm** [comment]
Проект вот на этом шаблоне https://packagist.org/packages/sganz/yii2-advanced-api-template модуль подключаю в backend

**Comment by Mirocow** [comment]
это старый и не нужный функционал, я его или выпилю и переделю

**Comment by Elgorm** [comment]
А чем сейчас пользоваться?

**Comment by Mirocow** [comment]
https://github.com/Mirocow/yii2-eav/blob/master/README.md

**Comment by Elgorm** [comment]
Спасибо.
