### ISSUE TITLE
Trying to get property of non-object

### ISSUE THREAD

**Issue by serjlaw** [Mirocow/yii2-eav#82]
Пытаюсь создать атрибут.
Получаю Trying to get property of non-object
Ругается на /vendor/mirocow/yii2-eav/src/models/EavAttribute.php ->
public function getRequired()
        {
                return $this->attributeRule->required;
        }

**Comment by Mirocow** [comment]
а можно весь трейс?

**Comment by serjlaw** [comment]
Вообщем запустил из вьюхи потому и не работало.
Итого по списку
- Энтити добавил.
- Аттрибут добавил.
- Но когда добавляю значение атрибута: Setting unknown property: app\models\Product::sky

**Comment by Mirocow** [comment]
Рулём является не обязательной, предложи вариант как лучше сделать

**Comment by serjlaw** [comment]
1. Если является необязательной, то почему ругается когда ее нет?
2. И кстати value вот так не добавляется:
$model = Product::findOne(1);
$model->sky = "263513";
$model->save();
говорит что нет такого атрибута..
