### ISSUE TITLE
Ошибка, при повторном сохранении

### ISSUE THREAD

**Issue by kowap** [Mirocow/yii2-eav#87]
`SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: '6,7,8,9,10,11,12,13,14,15,16,17,18,19,20'

The SQL being executed was: DELETE FROM `eav_attribute_value` WHERE ((`entityId`=1) AND (`attributeId`=2)) AND (optionId NOT IN ('6,7,8,9,10,11,12,13,14,15,16,17,18,19,20'))`

проблема в (optionId NOT IN ('6,7,8,9,10,11,12,13,14,15,16,17,18,19,20'))
числа в кавычках

**Comment by Mirocow** [comment]
спасибо, посмотрю
